# exports paths and other variables first
source "$HOME/.atuin/bin/env"
export ATUIN_NOBIND="true"
export PATH=$PATH:$HOME/bin
export SYSTEMD_EDITOR=nvim
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export HISTTIMEFORMAT="%F %T "
export HISTSIZE="100000"
export HISTFILESIZE="$HISTSIZE"
shopt -s histappend
PROMPT_COMMAND='history -a'
export LS_OPTIONS='--color=auto'
# and then aliases and such
if [[ -f ~/.bashrc ]]; then
  source ~/.bashrc
fi
