if [[ $- == *i* ]] # execute if in interactive shell
then
  PS1='\[\033[1;37m\][`date +%H:%M:%S`]\[\033[1;36m\][\[\033[1;31m\]\u\[\033[1;33m\]@\[\033[1;32m\]\h:\[\033[1;35m\]\w\[\033[1;36m\]]\[\033[1;31m\]\\$\[\033[0m\] '
  shopt -s extglob
  source -- /usr/local/lib/blesh/ble.sh --attach=none
  eval "$(atuin init bash)"
  bind -x '"\C-q": __atuin_history'
  source /usr/share/fzf/shell/key-bindings.bash
  alias cat='bat --style=plain --paging=never'
  if [[ $PS1 && -f /usr/share/bash-completion/bash_completion ]]
  then
    source /usr/share/bash-completion/bash_completion
  fi
fi

umask 022
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'
alias ..='cd ..'
alias ...='cd ../..'
alias vi='nvim'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

if [[ $- == *i* ]] # execute if in interactive shell
then
 [[ ! ${BLE_VERSION-} ]] || ble-attach
fi
