[commands]
upgrade_type = default
random_sleep = 0
network_online_timeout = 60
download_updates = yes
apply_updates = yes
reboot = never
reboot_command = "shutdown -r +5 'Rebooting after applying package updates'"
[emitters]
emit_via = stdio,email
[email]
email_from = root@@HOSTNAME@
email_to = ops@example.com
email_host = localhost
[command]
[command_email]
[base]
debuglevel = 2
